name: Deploy to GitHub Pages

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "50 18 */3 * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build -- --prefix-paths
        env:
          TWITTER: ${{ secrets.TWITTER }}
      - name: Deploy to gh-pages branch
        run: |
          cd public
          ORIGIN=https://${{ github.repository_owner }}:${{ github.token }}@github.com/${{ github.repository }}.git
          git init -b gh-pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Deploy gh-pages"
          git push -uf $ORIGIN gh-pages
